import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  componentsSidebar: [{type: 'autogenerated', dirName: 'components'}],
  tutorialsSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  stylesSidebar: [{type: 'autogenerated', dirName: 'styles'}],
};

export default sidebars;
