
import * as d from './components';

export const DIRECTIVES = [
  d.JeAlert,
  d.JeBranch,
  d.JeButton,
  d.JeCard,
  d.JeCheckbox,
  d.JeCheckboxGroup,
  d.JeCheckboxOption,
  d.JeColor,
  d.JeColumn,
  d.JeColumnGroup,
  d.JeDatepicker,
  d.JeDetails,
  d.JeDivider,
  d.JeDrawer,
  d.JeDropzone,
  d.JeForm,
  d.JeIcon,
  d.JeInfinite,
  d.JeInput,
  d.JeLink,
  d.JeLoading,
  d.JeMenu,
  d.JeMenuOption,
  d.JeModal,
  d.JeMultiselect,
  d.JeMultiselectOption,
  d.JePage,
  d.JePill,
  d.JePlaceholder,
  d.JePopover,
  d.JeRadio,
  d.JeRadioGroup,
  d.JeSelect,
  d.JeSelectOption,
  d.JeTab,
  d.JeTabs,
  d.JeTextarea,
  d.JeToast,
  d.JeToggle,
  d.JeToolbar,
  d.JeTree
];
